# config datasource for Jpa and Jdbc
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/storage?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: true
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
      hibernate:
        generate_statistics: true
  hibernate:
    cache:
      use_second_level_cache: true
      use_query_cache: true
      region:
        factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory